# Generated by Django 6.0.6 on 2026-06-14 21:12

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0001_initial'),
        ('groups', '0001_initial'),
        ('imports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=15)),
                ('original_amount', models.DecimalField(decimal_places=4, max_digits=15)),
                ('exchange_rate', models.DecimalField(decimal_places=8, default=Decimal('1.00000000'), max_digits=20)),
                ('converted_amount', models.DecimalField(decimal_places=4, max_digits=15)),
                ('expense_date', models.DateField(db_index=True)),
                ('split_type', models.CharField(choices=[('EQUAL', 'Equal'), ('PERCENTAGE', 'Percentage'), ('EXACT', 'Exact Amount'), ('SHARES', 'Shares')], db_index=True, default='EQUAL', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('receipt_url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_expenses', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='currencies.currency')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_expenses', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='groups.group')),
                ('import_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_expenses', to='imports.importjob')),
                ('original_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='original_expenses', to='currencies.currency')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paid_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'db_table': 'expenses',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseSplit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Raw split input value (percentage, shares, or exact amount)', max_digits=15)),
                ('share_percentage', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=8)),
                ('share_units', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('owed_amount', models.DecimalField(decimal_places=4, help_text='Final amount this user owes for this expense', max_digits=15)),
                ('is_settled', models.BooleanField(db_index=True, default=False)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='expenses.expense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_splits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense Split',
                'verbose_name_plural': 'Expense Splits',
                'db_table': 'expense_splits',
            },
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['group', 'expense_date'], name='expenses_group_i_8cd23b_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['group', 'is_deleted'], name='expenses_group_i_14ca95_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['paid_by', 'expense_date'], name='expenses_paid_by_69ef44_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='expensesplit',
            unique_together={('expense', 'user')},
        ),
    ]
