# Generated by Django 6.0.6 on 2026-06-14 21:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARSING', 'Parsing'), ('AWAITING_APPROVAL', 'Awaiting Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('rows_total', models.IntegerField(default=0)),
                ('rows_imported', models.IntegerField(default=0)),
                ('rows_skipped', models.IntegerField(default=0)),
                ('anomalies_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('report_path', models.CharField(blank=True, max_length=500, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='groups.group')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Import Job',
                'verbose_name_plural': 'Import Jobs',
                'db_table': 'import_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportAnomaly',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('raw_data', models.JSONField()),
                ('anomaly_type', models.CharField(choices=[('DUPLICATE_EXACT', 'Exact Duplicate'), ('DUPLICATE_POSSIBLE', 'Possible Duplicate'), ('NEGATIVE_VALUE', 'Negative Value'), ('SETTLEMENT_AS_EXPENSE', 'Settlement Recorded as Expense'), ('MISSING_PAYER', 'Missing Payer'), ('INVALID_DATE', 'Invalid Date'), ('FUTURE_DATE', 'Future Date'), ('CURRENCY_MISMATCH', 'Currency Mismatch'), ('UNKNOWN_MEMBER', 'Unknown Member'), ('MEMBER_NOT_ACTIVE', 'Member Not Active on Expense Date'), ('INCONSISTENT_SPLIT', 'Inconsistent Split Total'), ('MALFORMED_ROW', 'Malformed Row'), ('BLANK_MANDATORY_FIELD', 'Blank Mandatory Field'), ('CONFLICTING_DUPLICATE', 'Conflicting Duplicate Entry'), ('AMOUNT_OUTLIER', 'Amount Outlier')], db_index=True, max_length=30)),
                ('severity', models.CharField(choices=[('ERROR', 'Error'), ('WARNING', 'Warning'), ('INFO', 'Info')], db_index=True, max_length=10)),
                ('description', models.TextField()),
                ('recommendation', models.TextField()),
                ('action_taken', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('AUTO_RESOLVED', 'Auto Resolved')], db_index=True, default='PENDING', max_length=15)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_anomalies', to=settings.AUTH_USER_MODEL)),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='imports.importjob')),
            ],
            options={
                'verbose_name': 'Import Anomaly',
                'verbose_name_plural': 'Import Anomalies',
                'db_table': 'import_anomalies',
                'ordering': ['row_number', 'severity'],
            },
        ),
    ]
